services:
  - type: web
    name: siclox-backend
    env: node
    buildCommand: cd .. && npm install && cd backend && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        fromService:
          name: resend
          type: env
          property: apiKey
    build:
      npmInstall:
        enabled: true
        nodeVersion: 18.x  # Asegúrate de usar una versión compatible
    plan: free

secrets:
  - key: resend
    name: Resend API Key
    description: API Key para el servicio de Resend
    generateValue: false
