services:
  - type: web
    name: siclox-backend
    dockerfile: backend/Dockerfile
    env: docker
    envVars:
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        fromService:
          name: resend
          type: env
          property: apiKey
    build:
      docker:
        dockerfile: backend/Dockerfile
    plan: free

secrets:
  - key: resend
    name: Resend API Key
    description: API Key para el servicio de Resend
    generateValue: false
